/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kontaktlista;

//import java.util.ArrayList;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author okama01
 */
public class NewJFrame extends javax.swing.JFrame {

    // Kontakt[] konlista = new Kontakt[100];
    //  static ArrayList<Kontakt> konlista = new ArrayList<>();
    FileManager fmgr = new FileManager();
    DbManager db = new DbManager();
    String idnummer;

    //int antalkontakt = 0;
    //  Kontakt kon = new Kontakt(förnamn, efternamn, telefonnummer);
    /*    konLista.add(kon);
        Kontakt kon1 = konLista.get(0);
        for (int i = 0; i < konLista.size(); i++) {
            System.out.println(i);
        }*/
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbtnGroup = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbxFörnamn = new javax.swing.JTextField();
        tbxEfternamn = new javax.swing.JTextField();
        rbtfornamn = new javax.swing.JRadioButton();
        rbnefternamn = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextA = new javax.swing.JTextArea();
        läggtill = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        spara = new javax.swing.JButton();
        hämta = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        deleteTxt = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Förnamn ");

        jLabel2.setText("Efternamn");

        tbxFörnamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxFörnamnActionPerformed(evt);
            }
        });

        rbtnGroup.add(rbtfornamn);
        rbtfornamn.setSelected(true);
        rbtfornamn.setText("Förnamn Först");
        rbtfornamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtfornamnActionPerformed(evt);
            }
        });

        rbtnGroup.add(rbnefternamn);
        rbnefternamn.setText("Efternamn Först");
        rbnefternamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnefternamnActionPerformed(evt);
            }
        });

        TextA.setColumns(20);
        TextA.setRows(5);
        jScrollPane1.setViewportView(TextA);

        läggtill.setText("Lägg Till");
        läggtill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                läggtillActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Telefonnummer");

        spara.setText("spara");
        spara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparaActionPerformed(evt);
            }
        });

        hämta.setText("hämta");
        hämta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hämtaActionPerformed(evt);
            }
        });

        btnDelete.setText("delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        deleteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(rbtfornamn)
                        .addGap(38, 38, 38)
                        .addComponent(rbnefternamn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deleteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDelete))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbxFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tbxEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(läggtill)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(spara)
                                    .addComponent(hämta))))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(spara)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hämta)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDelete)
                            .addComponent(deleteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(tbxFörnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tbxEfternamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(läggtill))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtfornamn)
                    .addComponent(rbnefternamn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtfornamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtfornamnActionPerformed
        this.TextA.setText("");
        skrivUtFörnamn();
    }//GEN-LAST:event_rbtfornamnActionPerformed

    private void tbxFörnamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxFörnamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxFörnamnActionPerformed

    private void läggtillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_läggtillActionPerformed
        String förnamn = this.tbxFörnamn.getText(); // läser av textboxen
        this.tbxFörnamn.setText(""); // tömmer textboxer

        String efternamn = this.tbxEfternamn.getText();// läser av textboxen
        this.tbxEfternamn.setText(""); // tömmer textboxer

        String telefonnummer = this.jTextField1.getText();// läser av textboxen
        this.jTextField1.setText("");

        if (förnamn.contentEquals("") && efternamn.contentEquals("") && telefonnummer.contentEquals("")) { // om alla rader är tomma, finns ingen infromation- körs ingenting

        } else {
            Kontakt kon = new Kontakt(förnamn, efternamn, telefonnummer);
            db.insert(kon);

            if (rbtfornamn.isSelected()) { // man man väljer fornman först
                //    this.TextA.setText(""); //tomma rad
                skrivUtFörnamn();

            } else {

                skrivUtEfternamn();

            }

        }

    }//GEN-LAST:event_läggtillActionPerformed

    private void skrivUtFörnamn() {
        this.TextA.setText("");
        ResultSet rs = db.getAllData();
        if (rs != null) {
            try {
                while (rs.next()) {
                    this.TextA.append(rs.getInt("kontaktid") + "\t"
                            + rs.getString("firstname") + "\t"
                            + rs.getString("lastname") + "\t"
                            + rs.getString("phonenumber") + "\n");
                }
            } catch (SQLException ex) {
                System.out.println("Ingen data.");
            }
        } else {
            System.out.println("Ingen data från databasen, kontrollera anslutningen.");
        }

    }

    private void skrivUtEfternamn() {
        this.TextA.setText("");

        ResultSet rs = db.getAllData();
        if (rs != null) {
            try {
                while (rs.next()) {
                    this.TextA.append(rs.getInt("kontaktid") + "\t"
                            + rs.getString("lastname") + "\t"
                            + rs.getString("firstname") + "\t"
                            + rs.getString("phonenumber") + "\n");
                }
            } catch (SQLException ex) {
                System.out.println("Ingen data.");
            }
        } else {
            System.out.println("Ingen data från databasen, kontrollera anslutningen.");
        }
    }
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void rbnefternamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnefternamnActionPerformed
        this.TextA.setText("");
        skrivUtEfternamn();

    }//GEN-LAST:event_rbnefternamnActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        db.delete(number);
        if (rbtfornamn.isSelected()) { // man man väljer fornman först
                //    this.TextA.setText(""); //tomma rad
                skrivUtFörnamn();

            } else {

                skrivUtEfternamn();

            }
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void hämtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hämtaActionPerformed
        this.TextA.setText("");
        skrivUtFörnamn();
        /*   konlista = FileManager.readFromFile();
        this.TextA.setText("");
        for (int i = 0; i < konlista.size(); i++) {
            this.TextA.append(konlista.get(i).getfornamn() + "\t" + konlista.get(i).getefternamn() + "\t" + konlista.get(i).gettelefonnummer() + "\n");
        }*/
    }//GEN-LAST:event_hämtaActionPerformed

    private void sparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparaActionPerformed

    }//GEN-LAST:event_sparaActionPerformed

    private void deleteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteTxtActionPerformed

        idnummer = this.deleteTxt.getText();
        this.deleteTxt.setText("");
        int number = Integer.parseInt(idnummer);
        
        


    }//GEN-LAST:event_deleteTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {

        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NewJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextA;
    private javax.swing.JButton btnDelete;
    private javax.swing.JTextField deleteTxt;
    private javax.swing.JButton hämta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton läggtill;
    private javax.swing.JRadioButton rbnefternamn;
    private javax.swing.JRadioButton rbtfornamn;
    private javax.swing.ButtonGroup rbtnGroup;
    private javax.swing.JButton spara;
    private javax.swing.JTextField tbxEfternamn;
    private javax.swing.JTextField tbxFörnamn;
    // End of variables declaration//GEN-END:variables
}
